version: '3.8'
services:
  web:
    build: ./backend
    ports:
      - "5000:5000" # mapping the external port 5555 to container's internal port 5000 (on your computer use localhost:5555)
    environment: # environment variables required for flask
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - MONGODB_URI=mongodb+srv://guan:Aa123456@abandon.wga0hxr.mongodb.net/?retryWrites=true&w=majority&appName=Abandon
      - EMAIL_USERNAME=G506404@163.com
      - EMAIL_PASSWORD=WPQVZCBSVQEKCHYE
    volumes:
      - ./backend:/app # similar to below, this means when we make flask changes, it reloads in container
    command: flask run --host=0.0.0.0 --reload # this overrides the CMD in the Dockerfile and runs flask
    
 